[package]
name = "edra"
version = "0.1.1"
edition = "2021"

[dependencies]
serde = { version = "1.0.218", features = ["derive"] }
rand = "0.9.0"
chrono = "0.4.40"
bcrypt = "0.17.0"
derive_more = { version = "1.0.0", features = ["from"] }
p12 = "0.6.3"
pdf-writer = "0.13.0"
serde_json = "1.0.140"